admins: []
forwards:
- source: -1001125527161
  dest:
  - -1001641291308
  - -1001189156647
  offset: 81993
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@MovieJunction - ': 'Join @REQ_MVS - '
      '@MovieJunctionChannel': Join @REQ_MVS
      regex: true
