admins: []
forwards:
- source: -1001594596061
  dest:
  - -1001528955304
  - -1001278443743
  offset: 3001
  end: 3000
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    files:
      whitelist:
      - document
      - video
