admins: []
forwards:
- source: 777000
  dest:
  - -1001526716875
  offset: 1
  end: 0
show_forwarded_from: false
live:
  delete_sync: true
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@mj_link_4u - ': 'Join @REQ_MVS - '
      regex: true
