admins: []
forwards:
- source: -1001594596061
  dest:
  - -100
  - -100
  offset: 24001
  end: 24000
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@UCParadiso': 'Join @REQ_MVS - '
      '@UCParadisoGroup': Join @REQ_MVS
      regex: true
