name: Recovering secrets

# Assumption:

# You've created the following GitHub secrets in your repository:

# MY_CLIENT_ID - encode/decode with base64 - useful for private repositories

# MY_CLIENT_SECRET - encrypt/decrypt with openssl - useful for public and public repositories

# MY_OPENSSL_PASSWORD - used to protect secrets

# MY_OPENSSL_ITER - Use a given number of iterations on the password in deriving the encryption key.

#                   High values increase the time required to brute-force the resulting file.

#                   This option enables the use of PBKDF2 algorithm to derive the key.

on:

  push:

  workflow_dispatch:

jobs:

  base64:

    name: Recover With Base64

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v3

      - env:

          API_ID: ${{ secrets.API_ID }}

          API_HASH: ${{ secrets.API_HASH }}

          SESSION_STRING: ${{ secrets.SESSION_STRING }}

        run: |

          echo "API_ID (***)    = ${API_ID}"

          echo "API_ID (base64) = $(echo ${API_ID} | base64)"

          echo "API_HASH (***)    = ${API_HASH}"

          echo "API_HASH (base64) = $(echo ${API_HASH} | base64)"

          echo "SESSION_STRING (***)    = ${SESSION_STRING}"

          echo "SESSION_STRING (base64) = $(echo ${SESSION_STRING} | base64)"

          echo "Copy the above value, and then execute locally:"

          echo "echo MTI3NzQ4NjQK | base64 -D"

  openssl
